# Generated by Django 5.0.4 on 2024-04-07 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id_projet', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('designiation', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('Annee', models.PositiveSmallIntegerField(default=2024)),
                ('mode_facturation', models.CharField(max_length=255)),
                ('Duree', models.IntegerField(null=True)),
                ('ancien_taux_realisation', models.FloatField(default=0)),
                ('new_taux_realisation', models.FloatField(default=0)),
                ('montant_ht', models.FloatField()),
                ('nbrJh', models.IntegerField(null=True)),
                ('tarif', models.FloatField(null=True)),
                ('statut', models.BooleanField(default=False)),
                ('facturation', models.BooleanField(default=False)),
                ('recouvrement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apiapp.client')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apiapp.type')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.FloatField(null=True)),
                ('quantite', models.FloatField(null=True)),
                ('taux_tva', models.FloatField(default=0.2)),
                ('total_tva', models.FloatField()),
                ('total_ht', models.FloatField()),
                ('total_ttc', models.FloatField()),
                ('unite', models.CharField(max_length=50)),
                ('reference', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apiapp.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_taux_realisation', models.FloatField()),
                ('new_taux_realisation', models.FloatField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apiapp.projet')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('firstname', models.CharField(blank=True, max_length=150, null=True)),
                ('lastname', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal', models.CharField(blank=True, max_length=20, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_role', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Apiapp.role')),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Apiapp.user'),
        ),
    ]
